/**
 * State Machine Types
 *
 * Type definitions for the Idle-Detection State Machine.
 *
 * CRITICAL: The system must NEVER be in an idle state!
 * This module defines all types for detecting and preventing workflow stalls.
 */

// =============================================================================
// Board State Types
// =============================================================================

/**
 * Snapshot of the current board state for evaluation
 */
export interface BoardState {
  /** Number of tasks in backlog (unrefined/refined) */
  backlog: number;
  /** Number of refined tasks ready for sprint */
  backlogRefined: number;
  /** Number of tasks ready to be picked up */
  todo: number;
  /** Number of tasks currently in development */
  inProgress: number;
  /** Number of tasks waiting for review */
  inReview: number;
  /** Number of completed tasks */
  done: number;
  /** Number of blocked tasks */
  blocked: number;
  /** List of agents currently without assigned work */
  idleDevelopers: IdleAgentInfo[];
  /** List of agents currently working */
  busyDevelopers: BusyAgentInfo[];
  /** Total story points in backlog */
  backlogPoints: number;
  /** Total story points in todo */
  todoPoints: number;
  /** Total story points in progress */
  inProgressPoints: number;
  /** Timestamp when state was captured */
  capturedAt: string;
}

/**
 * Information about an idle agent
 */
export interface IdleAgentInfo {
  id: string;
  name: string;
  role: string;
  idleSince: string;
  capabilities: string[];
}

/**
 * Information about a busy agent
 */
export interface BusyAgentInfo {
  id: string;
  name: string;
  role: string;
  currentTaskId: string;
  currentTaskTitle: string;
  workingOnSince: string;
}

// =============================================================================
// Action Types
// =============================================================================

/**
 * Types of actions the state machine can trigger
 */
export type ActionType =
  | 'notify_developers' // Notify devs about available work
  | 'notify_po' // Notify Product Owner
  | 'notify_scrum_master' // Notify Scrum Master / Tech Lead
  | 'trigger_sprint_planning' // Trigger Sprint Planning event
  | 'trigger_backlog_refinement' // Trigger Backlog Refinement event
  | 'trigger_review_request' // Request code review
  | 'auto_assign_task' // Auto-assign task to idle developer
  | 'escalate_to_board' // Escalate to board/stakeholders
  | 'log_state_change'; // Log state change for audit

/**
 * Priority levels for actions
 */
export type ActionPriority = 'low' | 'medium' | 'high' | 'critical';

/**
 * An action to be executed by the state machine
 */
export interface StateMachineAction {
  /** Unique ID for this action */
  id: string;
  /** Type of action to take */
  type: ActionType;
  /** Priority of this action */
  priority: ActionPriority;
  /** Human-readable message */
  message: string;
  /** Detailed description */
  description: string;
  /** Target agents for notifications */
  targetAgentIds?: string[];
  /** Additional context data */
  context?: Record<string, unknown>;
  /** Event name if triggering a Scrum event */
  event?: string;
  /** Task to assign if auto-assigning */
  taskId?: string;
  /** Agent to assign to if auto-assigning */
  assignToAgentId?: string;
  /** Timestamp when action was created */
  createdAt: string;
}

// =============================================================================
// Rule Types
// =============================================================================

/**
 * A rule that the state machine evaluates
 */
export interface StateRule {
  /** Unique ID for this rule */
  id: string;
  /** Human-readable name */
  name: string;
  /** Description of what this rule detects */
  description: string;
  /** Priority of actions generated by this rule */
  priority: ActionPriority;
  /** Function to check if rule condition is met */
  condition: (state: BoardState) => boolean;
  /** Function to generate actions when condition is true */
  actions: (state: BoardState) => StateMachineAction[];
}

// =============================================================================
// Evaluation Result Types
// =============================================================================

/**
 * Result of evaluating board state
 */
export interface EvaluationResult {
  /** Whether the board is in a healthy state */
  healthy: boolean;
  /** Actions to take to improve the state */
  actions: StateMachineAction[];
  /** Rules that triggered actions */
  triggeredRules: string[];
  /** Summary message */
  summary: string;
  /** Timestamp of evaluation */
  evaluatedAt: string;
  /** The board state that was evaluated */
  boardState: BoardState;
}

// =============================================================================
// State Machine Configuration
// =============================================================================

/**
 * Configuration for the state machine
 */
export interface StateMachineConfig {
  /** Minimum number of refined backlog items to maintain */
  minBacklogSize: number;
  /** Polling interval in milliseconds (default: 5 minutes) */
  pollingIntervalMs: number;
  /** Whether to auto-assign tasks to idle developers */
  autoAssignEnabled: boolean;
  /** Maximum time a developer can be idle before notification (ms) */
  maxIdleTimeMs: number;
  /** Whether to send notifications */
  notificationsEnabled: boolean;
  /** Custom rules to add */
  customRules?: StateRule[];
}

/**
 * Default configuration
 */
export const DEFAULT_CONFIG: StateMachineConfig = {
  minBacklogSize: 5,
  pollingIntervalMs: 5 * 60 * 1000, // 5 minutes
  autoAssignEnabled: false, // Disabled by default, respect agent autonomy
  maxIdleTimeMs: 30 * 60 * 1000, // 30 minutes
  notificationsEnabled: true,
};

// =============================================================================
// State Machine State
// =============================================================================

/**
 * Internal state of the state machine
 */
export interface StateMachineState {
  /** Whether the state machine is running */
  running: boolean;
  /** Last evaluation result */
  lastEvaluation: EvaluationResult | null;
  /** History of evaluations (last N) */
  evaluationHistory: EvaluationResult[];
  /** Pending actions that haven't been executed yet */
  pendingActions: StateMachineAction[];
  /** Actions that have been executed */
  executedActions: ExecutedAction[];
  /** Configuration */
  config: StateMachineConfig;
  /** Last poll timestamp */
  lastPollAt: string | null;
  /** Number of consecutive healthy evaluations */
  healthyStreak: number;
  /** Number of consecutive unhealthy evaluations */
  unhealthyStreak: number;
}

/**
 * Record of an executed action
 */
export interface ExecutedAction {
  action: StateMachineAction;
  executedAt: string;
  success: boolean;
  error?: string;
  result?: unknown;
}

// =============================================================================
// Logging Types
// =============================================================================

/**
 * State change log entry
 */
export interface StateChangeLog {
  id: string;
  timestamp: string;
  previousState: Partial<BoardState>;
  currentState: BoardState;
  changes: StateChange[];
  triggeredActions: string[];
}

/**
 * Individual state change
 */
export interface StateChange {
  field: keyof BoardState;
  previousValue: unknown;
  currentValue: unknown;
  delta?: number;
}
